# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/160CJGeCkd0OL0fNisL3aDJaOgbbIUmsX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Creating simple dataset
data = {
    "Area": [500, 800, 1200, 1500, 2000, 2500],
    "Price": [150000, 200000, 300000, 350000, 450000, 500000]
}

df = pd.DataFrame(data)

X = df[["Area"]]
y = df["Price"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# Visualization
plt.scatter(X, y, color="blue")
plt.plot(X, model.predict(X), color="red")
plt.xlabel("Area")
plt.ylabel("Price")
plt.title("Linear Regression - House Price Prediction")
plt.show()